Nhom4_LTWeb/Controllers/BinhLuanController.cs
using Nhom4_LTWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Nhom4_LTWeb.Controllers
{
    public class BinhLuanController : Controller
    {
        // GET: BinhLuan
        DbMyWebDataContext db = new DbMyWebDataContext();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CommentPartial(int masp,string url) {
            GetALLModel item = new GetALLModel();
            item.GetBINHLUANModels = db.BINH_LUANs.Where(n=>n.MaSP == masp);
            item.GetKHACHHANGModels = db.KHACHHANGs;
            item.GetSANPHAMModels = db.SANPHAMs.Where(n=>n.MaSP==masp);
            return PartialView(item);
        }
        public ActionResult ThemComment(int MaSP,int ?MaTK,string BinhLuan,string url)
        {
            if (MaTK == null)
            {
                return RedirectToAction("DangNhap", "Account", new { url = url });
            }
            if (String.IsNullOrEmpty(BinhLuan) || BinhLuan.Equals("") || BinhLuan.Equals(""))
            {
                return Redirect(url);
            }
            else
            {
                BINH_LUAN bl = new BINH_LUAN();
                bl.MaSP = MaSP;
                bl.MaTK = MaTK;
                bl.BinhLuan = BinhLuan;
                db.BINH_LUANs.InsertOnSubmit(bl);
                db.SubmitChanges();
            }
            return Redirect(url);
        }
        public ActionResult XoaBinhLuan(int MaSP,int ?MaTK,string url)
        {
            BINH_LUAN bn = db.BINH_LUANs.Where(n=>n.MaSP == MaSP && n.MaTK == MaTK).Take(1).SingleOrDefault();
            if(bn != null)
            {
                db.BINH_LUANs.DeleteOnSubmit(bn);
                db.SubmitChanges();
            }

            return Redirect(url);
        }
        public ActionResult SuaBinhLuan(int MaSP,int ? MaTK,string BinhLuan,string url)
        {
            BINH_LUAN bl = new BINH_LUAN();
            bl.MaSP = MaSP;
            bl.MaTK = MaTK;
            bl.BinhLuan = BinhLuan.ToString();
            if(String.IsNullOrEmpty(BinhLuan) || BinhLuan == "" || BinhLuan == " ")
            {
                ViewBag["ErrBinhLuan"] = "Khong duoc rong";
                
            }
            db.SubmitChanges();
            return Redirect(url);
        }
    }
}

Nhom4_LTWeb/Views/BinhLuan/CommentPartial.cshtml
@model Nhom4_LTWeb.Models.GetALLModel
    @{ 
        Nhom4_LTWeb.Models.KHACHHANG kh = (Nhom4_LTWeb.Models.KHACHHANG)@Session["UserName"];
    }

        <div class="binhluan col-md-8">
            <div class="row pb-3">
                <div class="nav nav-tabs justify-content-between">
                    <div class="nav-item">
                        <a class="nav-link bg-danger text-white active" aria-current="page" href="#"><h5>BÌNH LUẬN</h5></a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="container mx-4">
                    <div class="row">
                       
                        <form action="@Url.Action("ThemComment", "BinhLuan")" method="get" class="col-md-12 d-flex">
                            @if (kh != null)
                            {
                                <input type="text" class="visually-hidden" required value="@kh.MaTK" id="MaTK" name="MaTK" />
                            }
                            <input type="text" class="visually-hidden" required value="@Model.GetSANPHAMModels.Select(n=>n.MaSP).Take(1).SingleOrDefault()" id="MaSP" name="MaSP" />
                            <input type="text" class="visually-hidden" required value="@Request.Url.ToString()" id="url" name="url" />

                            <textarea class="col-md-11 mx-1" id="BinhLuan" name="BinhLuan" placeholder="Hãy nhập bình luận"></textarea>
                            <button class="btn border border-3 border-danger col-md-1"><i class="fa-regular fa-paper-plane text-danger w-100 my-2"></i></button>
                        </form>
                    </div>
                    </div>
                <div class="LoiBInhLuan mx-4">
                        <section class="gradient-custom">
                              <div class="container my-3">
                                <div class="row d-flex justify-content-center">
                                  <div class="col-md-12">
                                    <div class="card">
                                        <div class="card-body p-4">

                                            @foreach (var item in Model.GetBINHLUANModels)
                                            {
                                                <div class="row mt-1">
                                                    <div class="col">
                                                        <div class="d-flex flex-start">
                                                            <img class="rounded-circle shadow-1-strong me-3"
                                                                 src="~/image/download.png" alt="avatar" width="65"
                                                                 height="65" />
                                                            <div class="flex-grow-1 flex-shrink-1 border border-1 p-1 rounded-1">
                                                                <div>
                                                                    <div class="d-flex justify-content-between align-items-center">
                                                                        <p class="mb-1 fw-bold px-2">
                                                                            @Model.GetKHACHHANGModels.Where(n => n.MaTK == item.MaTK).Select(n => n.HoTen).Take(1).SingleOrDefault()
                                                                        </p>
                                                                    </div>
                                                                    <p class="small mb-0 px-2">
                                                                        @item.BinhLuan
                                                                    </p>
                                                                </div>
                                                            </div>

                                                        </div>
                                                        <div class="row">
                                                            <div class="col-md-9"></div>
                                                            <div class="comment col-md-3">
                                                                <a href="#" class="mx-2"><i class="fa-solid fa-comment"></i> Trả lời</a>
                                                                @if (kh != null)
                                                                {
                                                                    if (item.MaTK == kh.MaTK)
                                                                    {
                                                                        <a href="@Url.Action("XoaBinhLuan","BinhLuan",new { MaSP = @Model.GetSANPHAMModels.Select(n => n.MaSP).Take(1).SingleOrDefault(), MaTK = kh.MaTK,url = Request.Url.ToString()})" class="mx-2"> <i class="fa-solid fa-delete-left"></i> Xóa</a>
                                                                    }
                                                                }
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                            }
                                            @if(Model.GetBINHLUANModels.Count() == 0)
                                            {
                                                <div class="row mt-1">
                                                    <div class="col">
                                                        <h3>KHÔNG CÓ BÌNH LUẬN NÀO HẾT :)))))</h3>
                                                    </div>
                                                </div>
                                            }
                                        </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                        </section>
                </div>
            </div>
        </div>
    </div>