Nhom4_LTWeb/Controllers/LocSanPhamController.cs
using Microsoft.Ajax.Utilities;
using Nhom4_LTWeb.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlTypes;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;

namespace Nhom4_LTWeb.Controllers
{
    public class LocSanPhamController : Controller
    {
        // GET: LocSanPham
        DbMyWebDataContext db = new DbMyWebDataContext();

        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult SanDuLieu(int MaLSP = 0, int Mahang = 0, int RAM = 0, int CPU = 0, int SSD = 0, int HHD = 0, int MAINBOARD = 0,string TenSP = null)
        {
            GetALLModel item = new GetALLModel();
            item.GetSANPHAMModels = db.SANPHAMs;
            if (!String.IsNullOrEmpty(TenSP))
            {
                item.GetSANPHAMModels = db.SANPHAMs.Where(n=>n.TenSP.Contains(TenSP));
            }
            
            
            List<int> l = new List<int>();
            l.Add(RAM);
            l.Add(CPU);
            l.Add(SSD);
            l.Add(MAINBOARD);
            l.Add(HHD);
            if (MaLSP != 0 && Mahang != 0)
            {
                item.GetSANPHAMModels = db.SANPHAMs.Where(n => n.MaHang == Mahang && n.MaLSP == MaLSP);

            }
            else if (MaLSP != 0)
            {
                item.GetSANPHAMModels = db.SANPHAMs.Where(n => n.MaLSP == MaLSP);
            }
            else if (Mahang != 0)
            {
                item.GetSANPHAMModels = db.SANPHAMs.Where(n => n.MaHang == Mahang);
            }
            int tongChon = 0;
             foreach (int i in l)
            {
                if (i > 0)
                {
                    tongChon++;
                }

            }

            var kq = from n in db.CHITIET_SPs
                     group n by new { n.MaSP } into g
                     select new ChiTietSP
                     {
                         id = g.Key.MaSP,
                         count = g.Count()

                     };
            item.GetChiTietSPModels = kq;
            if (tongChon != 0)
            {
                kq = from n in db.CHITIET_SPs
                         where (n.MaThongSo == RAM || n.MaThongSo == CPU || n.MaThongSo == SSD || n.MaThongSo == MAINBOARD)
                         group n by new { n.MaSP } into g
                         select new ChiTietSP
                         {
                             id = g.Key.MaSP,
                             count = g.Count()

                         };
                item.GetChiTietSPModels = kq.Where(n => n.count == tongChon);
            }
            item.GetHANGModels = db.HANGs;
            item.GetsLOAISPModels = db.LOAISPs;
            item.GetTHE_CHITIETModels = db.THE_CHITIETs;
            item.GetTHEModels = db.THEs;
            return View(item);
        }
    }
}

Nhom4_LTWeb/Controllers/ShopController.cs
using Nhom4_LTWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Nhom4_LTWeb.Models;

namespace Nhom4_LTWeb.Controllers
{
    public class ShopController : Controller
    {
        // GET: Shop
        DbMyWebDataContext db = new DbMyWebDataContext();

        public ActionResult Index()
        {
            GetALLModel dulieu = new GetALLModel();
            KHACHHANG kh = (KHACHHANG)Session["Username"];
            int temp = 0;
            if(kh != null)
            {
                temp = kh.MaTK;
            }
            dulieu.GetSANPHAMModels = db.SANPHAMs.ToList();
            dulieu.GetHANGModels = db.HANGs.ToList();   
            dulieu.GetsLOAISPModels = db.LOAISPs.ToList();
            dulieu.GetHANG_LOAISPModels = db.HANG_LOAISPs.ToList();
            dulieu.GetWISHLISTModels = db.WISHLISTs.Where(n=>n.MaTK == temp);
            return View(dulieu);
        }
        public ActionResult Details(int masp)
        {
            GetALLModel dulieu = new GetALLModel();
            dulieu.GetSANPHAMModels = db.SANPHAMs.Where(n=>n.MaSP == masp).ToList();
            dulieu.GetHANGModels = db.HANGs.ToList();
            dulieu.GetsLOAISPModels = db.LOAISPs.ToList();
            dulieu.GetHANG_LOAISPModels = db.HANG_LOAISPs.ToList();
            dulieu.GetCHITIET_SPModels =db.CHITIET_SPs.ToList();
            dulieu.GetTHE_CHITIETModels = db.THE_CHITIETs.ToList();
            dulieu.GetTHEModels = db.THEs.ToList();
            return View(dulieu);
        }
        public ActionResult HeaderWebPartial()
        {
            return PartialView();
        }
        public ActionResult NavPartial()
        {
            GetALLModel item = new GetALLModel();
            item.GetHANGModels = db.HANGs;
            item.GetHANG_LOAISPModels = db.HANG_LOAISPs;
            item.GetTHEModels = db.THEs;
            item.GetTHE_CHITIETModels = db.THE_CHITIETs;
            item.GetsLOAISPModels = db.LOAISPs;
            return PartialView(item);
        }
        public ActionResult NavQCPartial()
        {
            
            return PartialView();
        }
        public ActionResult FooterPartial()
        {
            return PartialView();
        }
        public ActionResult ItemPartial()
        {
            return PartialView();
        }
    }
}

Nhom4_LTWeb/Views/Shop/FooterPartial.cshtml
<section class="myFooter bg-dark">
    <div class="container py-2">
        <div class="row d-flex justify-content-between">
            <div class="col-md-3 text-white">
                <h4>ĐỊA CHỈ</h4>
                <ul class="list-menu">
                    <li class="li_menu"><a href="/p/gioi-thieu.html" title="Giới thiệu" class="text-decoration-none text-white">Địa chỉ: 2/23 Đại lộ bình dương,TP Thủ dầu Một, Bình dương</a></li>
                </ul>
            </div>
            <div class="col-md-3 text-white">
                <h4>VỀ CHÚNG TÔI</h4>
                <ul class="list-menu">
                    <li class="li_menu"><a href="/" title="Trang chủ" class="text-decoration-none text-white">MUDA shop </a></li>
                    <li class="li_menu"><a href="/p/gioi-thieu.html" class="text-decoration-none text-white" title="Giới thiệu">Trang web chúng tôi chuyên về các sản phẩm công nghệ, với giá rẻ chúng tôi mong muốn có thể đáp ứng nhu cầu của bạn</a></li>
                </ul>
            </div>
            <div class="col-md-3 text-white">
                <h4>Tổng đài hổ trợ</h4>
                <ul class="list-menu">
                    <li class="li_menu"><a href="/p/gioi-thieu.html" class="text-decoration-none text-white"></a>18001090</li>
                    <li class="li_menu"><a href="/p/gioi-thieu.html" class="text-decoration-none text-white"></a>18001091</li>
                    <li class="li_menu"><a href="/p/gioi-thieu.html" class="text-decoration-none text-white"></a>18001092</li>
                </ul>
            </div>
        </div>
    </div>
</section>

Nhom4_LTWeb/Views/Shop/HeaderWebPartial.cshtml
@{ 
    Nhom4_LTWeb.Models.KHACHHANG kh = (Nhom4_LTWeb.Models.KHACHHANG)Session["UserName"];
    Session["null"] = null;
}

<section class="myHeader">
    <div class="container py-3 ">
        <div class="row">
            <div class="col-md-2 col-sm-12 py-sm img-fluid"><a href="@Url.Action("Index","Shop")"><img src="~/image/logo.png" alt="" srcset=""></a></div>
            <div class="col-md-1"></div>
            <div class="col-md-7">
                <div class="row">
                    <div class="col-md-8">
                        @using (Html.BeginForm("SanDuLieu", "LocSanPham", FormMethod.Get))
                        {
                            <div class="input-group mb-3 col-md d-flex">
                                <input type="text" class="form-control" type="text" name="TenSP" placeholder="Nhập sản phẩm bạn muốn tìm :3" aria-label="Recipient's username" aria-describedby="basic-addon2">
                                <button class="p-0 border-0 bg-white mx-1" ><span class="input-group-text p-3" id="basic-addon2"><i class="fa-solid fa-magnifying-glass"></i></span></button>
                                
                            </div>
                        }
                        </div>
                </div>
            </div>

            @if (kh != null)
            {
                <div class="col-md-2">
                    <div class="row">
                        <div class="col-md-3">
                            <a href="#" class="fa-solid fa-arrow-right-from-bracket py-3 text-danger" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true"></a>
                            <ul class="dropdown-menu">
                                <li class="dropdown-item"><a href="@Url.Action("ThongTin", "Account", new {id=kh.MaTK})">Thông tin</a></li>
                                <li role="separator" class="divider"></li>
                                <li class="dropdown-item"><a href="@Url.Action("DangXuat", "Account")">Đăng xuất</a></li>
                            </ul>
                        </div>

                        <div class="col-md-3"><a href="" class="text-danger"><i class="fa-solid fa-address-book py-3"></i></a></div>

                        <div class="col-md-3">
                            <a href="@Url.Action("WishList","WishList")" class="text-danger position-relative">
                                <span><i class="fa-regular fa-heart py-3"></i></span>
                                <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill text-bg-danger">
                                    @ViewBag.TongWL
                                </span>
                            </a>
                        </div>

                        <div class="col-md-3">
                            <a href="@Url.Action("GioHang","GioHang")" class="text-danger position-relative">
                                <span><i class="fa-solid fa-cart-shopping py-3"></i></span>
                                <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill text-bg-danger">
                                    @Html.Action("GioHangPartial", "GioHang")
                                </span>
                            </a>
                        </div>
                    </div>
                </div>
            }
            else
            {
                <div class="col-md-2">
                    <div class="row">
                        <div class="col-md-3">
                            <a href="#" class="fa-solid fa-user py-3 text-danger" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true"></a>
                            <ul class="dropdown-menu">
                                <li class="dropdown-item"><a href="@Url.Action("DangKy", "Account")">Đăng ký</a></li>
                                <li role="separator" class="divider"></li>
                                <li class="dropdown-item"><a href="@Url.Action("DangNhap", "Account", new {url = Request.Url.ToString()})">Đăng nhập</a></li>
                            </ul>
                        </div>

                        <div class="col-md-3"><a href="" class="text-danger"><i class="fa-solid fa-address-book py-3"></i></a></div>

                        <div class="col-md-3">
                            <a href="" class="text-danger position-relative">
                                <span><i class="fa-solid fa-cart-shopping py-3"></i></span>
                                <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill text-bg-danger">
                                    0
                                </span>
                            </a>
                        </div>

                        <div class="col-md-3">
                            <a href="@Url.Action("GioHang","GioHang")" class="text-danger position-relative">
                                <span><i class="fa-regular fa-heart py-3"></i></span>
                                <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill text-bg-danger">
                                   0
                                </span>
                            </a>
                        </div>

                    </div>
                </div>
            }

        </div>
    </div>
</section>

Nhom4_LTWeb/Views/Shop/Index.cshtml
@model Nhom4_LTWeb.Models.GetALLModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@Html.Action("NavQCPartial", "Shop")
<section class="MyBody py-2">
    <div class="container">
        @foreach (var item in Model.GetsLOAISPModels)
        {
            <div class="row">
                <div class="nav nav-tabs justify-content-between">
                    <div class="nav-item">
                        <a class="nav-link bg-danger text-white active" aria-current="page" href="@Url.Action("SanDuLieu","LocSanPham",new {maLSP = item.MaLSP})"><h1>@item.TenLoaiSP</h1></a>
                    </div>
                    <div class="nav-item">

                    </div>
                    <div class="nav navbar-expand-lg ">
                        @foreach (var item1 in Model.GetHANG_LOAISPModels.Where(n => n.MaLSP == item.MaLSP))
                        {
                            foreach (var item2 in Model.GetHANGModels.Where(c => c.MaHang == @item1.MaHang))
                            {
                                <li class="align-self-center nav-item mx-1"><a class="nav-link text-bg-danger rounded-1 px-1" role="button" href="@Url.Action("SanDuLieu","LocSanPham",new {maLSP = item1.MaLSP,maHang = item1.MaHang})"><p class="MYSP m-0 fw-bold">@item2.TenHang</p></a></li>
                            }
                        }
                        <li class="align-self-center nav-item mx-1"><a class="nav-link text-bg-danger rounded-1 px-1" role="button" href="#"><p class="MYSP m-0 fw-bold">Xem tất cả</p></a></li>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 col-lg-12 col-sm-12">
                        <div class="row py-3">
                            <div class="owl-carousel owl-theme">
                                @foreach (var sanpham in Model.GetSANPHAMModels.Where(n => n.MaLSP == item.MaLSP))
                                {
                                    <div class="img-thumbnail container item">
                                        <a href="@Url.Action("Details", "Shop", new { masp = sanpham.MaSP })" style="text-decoration:none;">
                                            <div class="overflow-hidden"><img src="~/Hinh/@sanpham.HinhAnh" alt="" srcset="" style="max-height:184px" /></div>
                                            <div class="container-fluid mb-4">
                                                <h3 class="fw-bold nameproduct py-3 text-dark">@sanpham.TenSP</h3>
                                                <div class="gia">
                                                    <p class="fw-bold text-danger mx-0">@sanpham.GiaSP đ</p>
                                                    <div class="gialendoi d-flex">
                                                       
                                                        <p class="fw-bold text-danger">@sanpham.GiaSP đ</p>
                                                    </div>
                                                </div>
                                            </div>
                                        </a>
                                        <div class="d-flex justify-content-between mx-2">
                                            <a href="@Url.Action("ThemWishList", "WishList", new { maSP = sanpham.MaSP, url = Request.Url.ToString() })" class="wishList align-self-center">@if (Model.GetWISHLISTModels.Where(n => n.MaSP == sanpham.MaSP).Count() > 0)
                                            {<i class="fa-solid fa-heart align-self-center text-danger"></i>}
                                            else { <i class="fa-solid fa-heart align-self-center"></i>}</a>

<a href="@Url.Action("ThemGioHang", "GioHang", new {maSP = sanpham.MaSP,url = Request.Url.ToString()})" class="btn btn-primary fw-bold" role="button"><i class="fa-solid fa-cart-shopping"></i></a>
                                        </div>
                                    </div>
                                }

                            </div>
                        </div>
                    </div>
                </div>

            </div>
        }

    </div>
</section>
@section FooterPartial{
    @Html.Action("FooterPartial", "Shop")
}

Nhom4_LTWeb/Views/Shop/NavPartial.cshtml
@model Nhom4_LTWeb.Models.GetALLModel
<section class="navbar bg-danger">

    <div class="container">
        <div class="row container">
            <div class="col-md-3">
                <nav class="navbar navbar-expand-lg bg-danger">
                    <div class="container-fluid">
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav  mb-2 mb-lg-0">
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Danh mục sản phẩm
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item text-dark">Laptop</a>
                                        <a class="dropdown-item text-dark">Máy tính</a>
                                        <a class="dropdown-item text-dark">Điện thoại</a>
                                        <a class="dropdown-item text-dark">Linh kiện</a>
                                    </div>
                                </li>

                            </ul>
                        </div>
                    </div>
                </nav>
            </div>

            <div class="col-md-9">
                <nav class="navbar navbar-expand-lg bg-danger">
                    <div class="container-fluid">
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav  mb-2 mb-lg-0">
                                <li class="nav-item">
                                    <a class="nav-link active text-white" aria-current="page" href="@Url.Action("Index","Shop")">Trang chủ</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" href="#">Bảo trì</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" href="#">Tin tức</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Sản phẩm
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" href="#">Action</a></li>
                                        <li><a class="dropdown-item" href="#">Another action</a></li>
                                        <li><hr class="dropdown-divider"></li>
                                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                                    </ul>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white " href="#">Giới thiệu</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" href="#">Liên hệ</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </div>
</section>

Nhom4_LTWeb/Views/Shop/NavQCPartial.cshtml
<section class="navQC">
    <div class="container">
        <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="~/Hinh/laptop surface.png" class="d-block w-100" height="500px" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="~/Hinh/maytinhasus.png" class="d-block w-100" height="500px" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="~/Hinh/laptop msi.png" class="d-block w-100" height="500px" alt="...">
                </div>
            </div>
            <button class="carousel-control-prev " type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>
</section>